### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [vinnyoodles/TRMosaicLayout#2]
<img width="427" alt="screen shot 2016-07-04 at 6 10 26 pm" src="https://cloud.githubusercontent.com/assets/6511079/16569905/ac29b876-4212-11e6-9f6b-3ce41b6693c8.png">

Should be something like:

> A mosaic collection view layout inspired by Lightbox's Algorithm, written in Swift 🔶

**Comment by vincent144** [comment]
Forgot about it, thank you!

**Comment by lfarah** [comment]
You're welcome 😉
