### ISSUE TITLE
Doesn't scroll when big one cell alone

### ISSUE THREAD

**Issue by vadimvitvickiy** [vinnyoodles/TRMosaicLayout#4]
Hello, found that problem, what is this? my mistake? Scrolling just stop, if there big one cell without 2 small, but i can see it while bouncing collectionview
I like your job, and want to implement in my project, but does it work only with even counts of items?

**Comment by vincent144** [comment]
It should work with any number of items without affecting the scrolling. The only thing it does affect is the layout. I'm not sure what the issue is, you're saying it doesn't scroll but it does bounce so I'm just a bit confused

**Comment by vadimvitvickiy** [comment]
final scroll, dont go deeper
![simulator screen shot 19 2016 19 16 32](https://cloud.githubusercontent.com/assets/5019512/16953148/c324663e-4ded-11e6-96f2-eb8fa8bad521.png)

dragged down (bouncing)
![simulator screen shot 19 2016 19 16 39](https://cloud.githubusercontent.com/assets/5019512/16953165/d51915ce-4ded-11e6-907b-e595634388a7.png)

**Comment by vadimvitvickiy** [comment]
content of scroll = small one, not big one

**Comment by vincent144** [comment]
Could you make a gif of this in action, it's hard to tell through still images

**Comment by vadimvitvickiy** [comment]
http://im.ezgif.com/tmp/ezgif-366586186.gif

**Comment by Nathan961207** [comment]
**Edit 2019-09-17: Is this workaround still being used or can I remove this?**
The way to fix this issue is to go into the TRMosaicColumns and change the following line:
```swift
import UIKit

struct TRMosaicColumns {


var columns:[TRMosaicColumn]

var smallestColumn:TRMosaicColumn {
   // return columns.sort().first! <---------------------------------------------! CHANGE THIS

    return columns.sort().last! <---------------------------------------------! TO THIS
}



init() {
    columns = [TRMosaicColumn](count: 3, repeatedValue: TRMosaicColumn())
}



subscript(index: Int) -> TRMosaicColumn {

    get {
        return columns[index]
    }

    set(newColumn) {

        columns[index] = newColumn

    }
}

```
---

Från: pluckq notifications@github.com
Skickat: den 19 juli 2016 12:54
Till: vinnyoodles/TRMosaicLayout
Ämne: [vinnyoodles/TRMosaicLayout] Doesn't scroll when big one cell alone (#4)

Hello, found that problem, what is this? my mistake? Scrolling just stop, if there big one cell without 2 small, but i can see it while bouncing collectionview
I like your job, and want to implement in my project, but does it work only with even counts of items?

##

**Comment by vincent144** [comment]
But doesn't the `sort()` return the array in ascending order? So the first element would ideally be the smallest?

**Comment by Alex293** [comment]
Hi, having the same issue to solve should I use Nathan solution or are you working on a fix ?

**Comment by vincent144** [comment]
Use @Nathan961207 's solution, I haven't been able to recreate the issue so I can't offer a better solution

**Comment by Alex293** [comment]
Fix is working fine thanks

**Comment by ratulSharker** [comment]
Please release this in cocoapod, Until then we ended up with following

```
  pod 'TRMosaicLayout', :git => 'https://github.com/vinnyoodles/mosaic-layout.git', :branch => 'master'
```
