### ISSUE TITLE
custom layout not attached

### ISSUE THREAD

**Issue by exocode** [vinnyoodles/TRMosaicLayout#5]
Hi there, 

I am sorry, to maybe ask a stupid question. 

I've installed all proberly. The demo is running nicely with the Asset book images. (y)

**Now my problem:**

I installed `TRMosaikLayout` by cocoapods. I am using XCode8 beta6.
I copied the `TRCollectionViewController` code into an empty `UICollectionViewController` class. 
I added a `UICollectionViewController` onto my storyboard
I changed the `reuseIdentifier` to the proberly name
Added the `Assets` you provide in your example
I changed the `cell color` to any color (for testing)
Run the project, but `cellForItemAt indexPath`**was never called**. 

After a few hours of doom, I commented out the 

```
   ` // self.collectionView!.collectionViewLayout = mosaicLayout`
```

 Now it **shows me the cells regularly. But not as Mosaiks**. When I comment in this line, the mosaiklayout stays empty. 

The `cellForItemAt indexPath` function don't get called.
## What I am missing, what should I do?

Many thanks in advance

**Comment by Nathan961207** [comment]
My biggest guess would be that your UICollectionViewController is a subclass of TRCollectionViewController so it is already using the 'mosaicLayout'.

---

Från: Jan notifications@github.com
Skickat: den 8 september 2016 15:31
Till: vinnyoodles/TRMosaicLayout
Ämne: [vinnyoodles/TRMosaicLayout] custom layout not attached (#5)

Hi there,

I am sorry, to maybe ask a stupid question.

I've installed all proberly. The demo is running nicely with the Asset book images. (y)

Now my problem:

I installed TRMosaikLayout by cocoapods. I am using XCode8 beta6.
I copied the TRCollectionViewController code into an empty UICollectionViewController class.
I added a UICollectionViewController onto my storyboard
I changed the reuseIdentifier to the proberly name
Added the Assets you provide in your example
I changed the cell color to any color (for testing)
Run the project, but cellForItemAt indexPathwas never called.

After a few hours of doom, I commented out the

   `// self.collectionView!.collectionViewLayout = mosaicLayout`

Now it shows me the cells.

What I am missing, what should I do?

Many thanks in advance

##

**Comment by exocode** [comment]
I cant explain why it not worked. Simply started from scratch,.. now it works.. made a PR for swift3 :-)
