### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [vinnyoodles/TRMosaicLayout#7]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by vincent144** [comment]
I'll try to merge in https://github.com/vinnyoodles/TRMosaicLayout/pull/6 this weekend

**Comment by lfarah** [comment]
Thanks, @vinnyoodles! 🎉

**Comment by vincent144** [comment]
Sorry for the delay, I wasn't able to push it yet because I'm still on the old Xcode 7. Will get it out ASAP

**Comment by christstuart** [comment]
@vinnyoodles any progress in the swift 3 implementation?

**Comment by vincent144** [comment]
Just updated 😄

**Comment by lfarah** [comment]
Thanks @vinnyoodles, you're awesome! 🎉
